require:
  - rubocop-capybara
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.3
  DisplayStyleGuide: true
  NewCops: enable
  Exclude:
    - "bin/*"
    - "db/migrate/*"
    - "db/schema.rb"

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "test/**/*"
  Max: 30
